<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" />
	  <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
	  <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" />
    <PackageReference Include="Pluralize.NET" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\CleanTemplate.Common.csproj" />
    <ProjectReference Include="..\..\Core\Application\CleanTemplate.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Persistance\CleanTemplate.Persistence.csproj" />
  </ItemGroup>

</Project>
