<Project Sdk="Microsoft.NET.Sdk.Web">

        <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <UserSecretsId>ef818a9d-a691-4993-b3e3-782c7cd390cf</UserSecretsId>
                <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
                <DockerfileContext>..\..\..</DockerfileContext>
                <PackageReadmeFile>README.md</PackageReadmeFile>
                <GenerateDocumentationFile>true</GenerateDocumentationFile>
                <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
        </PropertyGroup>

	<ItemGroup>
		<Folder Include="Controllers\v2\" />
	</ItemGroup>

        <ItemGroup>

                <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
                        <PrivateAssets>all</PrivateAssets>
                        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
                </PackageReference>

                <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
                <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
                <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
                <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
                <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
                <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
                <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
                <PackageReference Include="Microsoft.Extensions.Http.Polly" />
                <PackageReference Include="prometheus-net.AspNetCore" />

		<None Include="README.md" Pack="true" PackagePath="\" />

        </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\Application\CleanTemplate.Application.csproj" />
		<ProjectReference Include="..\ApiFramework\CleanTemplate.ApiFramework.csproj" />
	</ItemGroup>

</Project>
