trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true
  displayName: 'Install .NET SDK'

- script: dotnet restore CleanTemplate.sln
  displayName: 'Restore'

- script: dotnet build CleanTemplate.sln -c Release --no-restore
  displayName: 'Build'

- script: dotnet test CleanTemplate.sln -c Release --no-build --collect:"XPlat Code Coverage" --results-directory $(Build.SourcesDirectory)/TestResults
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'TestResults/**/testResults.trx'
    searchFolder: '$(Build.SourcesDirectory)/TestResults'
    testRunTitle: 'Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/TestResults'
    ArtifactName: 'TestResults'
