name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: true
      - name: Restore
        run: dotnet restore CleanTemplate.sln
      - name: Build
        run: dotnet build CleanTemplate.sln -c Release --no-restore
      - name: Test
        run: dotnet test CleanTemplate.sln -c Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
      - name: Generate coverage report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:TestResults/coverage -reporttypes:Html
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: TestResults/coverage
